/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_future_jonassen_GPIOImplementation_Hardware */

#ifndef _Included_com_future_jonassen_GPIOImplementation_Hardware
#define _Included_com_future_jonassen_GPIOImplementation_Hardware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    initGPIO
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_initGPIO
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    uninitGPIO
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_uninitGPIO
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    GPIOSetDir
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_GPIOSetDir
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    GPIOGetDir
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_GPIOGetDir
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    GPIOSetVal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_GPIOSetVal
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    GPIOGetVal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_GPIOGetVal
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_future_jonassen_GPIOImplementation_Hardware
 * Method:    getClanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_future_jonassen_GPIOImplementation_Hardware_getClanguageString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
